/* Generated by AN DISI Unibo */ 
package it.unibo.ctxtruck
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhsot", this, "waste_service.pl", "sysRules.pl","ctxtruck"
	)
}

