/* Generated by AN DISI Unibo */ 
package it.unibo.sonarlatestart

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonarlatestart ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_s0", 
							scope, context!!, "local_tout_sonarlatestart_s0", 8000.toLong() )
					}
					 transition(edgeName="t00",targetState="active",cond=whenTimeout("local_tout_sonarlatestart_s0"))   
				}	 
				state("active") { //this:State
					action { //it:State
						forward("cmdSonar", "cmd(activate)" ,"sonardata" ) 
					}
				}	 
			}
		}
}
