/* Generated by AN DISI Unibo */

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import java.lang.Exception

class Ledconcretefsm (name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	private var ledstate  = 0  // 0 off 1 blink 2 on

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | STARTS")
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
					}
					 transition(edgeName="t02",targetState="on",cond=whenDispatch("ledon"))
					transition(edgeName="t03",targetState="off",cond=whenDispatch("ledoff"))
					transition(edgeName="t04",targetState="blink",cond=whenDispatch("ledblink"))
				}	 
				state("on") { //this:State


					action { //it:State
						try {
							Runtime.getRuntime().exec("sudo bash led25GpioTurnOn.sh")

						} catch (e: Exception) {
							println("WARNING: ledConcrete does not find led25GpioTurnOn.sh")
						}
						ledstate = 2
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )


				}
				state("off") { //this:State
					action { //it:State

						try {
							Runtime.getRuntime().exec("sudo bash led25GpioTurnOff.sh")

						} catch (e: Exception) {
							println("WARNING: ledConcrete does not find led25GpioTurnOff.sh")
						}
						ledstate = 0
					}

					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("blink") { //this:State
					action { //it:State

						if (ledstate != 1) { /*only if is not already blinking*/
							try {
								Runtime.getRuntime().exec("sudo bash led25GpioBlink.sh")

							} catch (e: Exception) {
								println("WARNING: ledConcrete does not find led25GpioBlink.sh")
							}
							ledstate = 1
						}
					}

					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
}
