/* Generated by AN DISI Unibo */

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Ledsimulatorfsm ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name | STARTS")
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
					}
					 transition(edgeName="t02",targetState="on",cond=whenDispatch("ledon"))
					transition(edgeName="t03",targetState="off",cond=whenDispatch("ledoff"))
					transition(edgeName="t04",targetState="blink",cond=whenDispatch("ledblink"))
				}	 
				state("on") { //this:State
					action { //it:State

						unibo.actor22comm.utils.ColorsOut.outappl(
							"$name - on", unibo.actor22comm.utils.ColorsOut.MAGENTA
						)
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("off") { //this:State
					action { //it:State
						unibo.actor22comm.utils.ColorsOut.outappl(
							"$name - off", unibo.actor22comm.utils.ColorsOut.MAGENTA
						)

					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("blink") { //this:State
					action { //it:State

						unibo.actor22comm.utils.ColorsOut.outappl(
							"$name - blink", unibo.actor22comm.utils.ColorsOut.MAGENTA
						)

					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
}
